project:
  title: "fopra-slides"
  type: website
  output-dir: docs

bibliography: specifics/bib-local.bib
csl: specifics/apa7.csl



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



website:
  sidebar:
    left:
      - href: thema01.qmd
      - href: thema02.qmd
    search: true
