project:
  title: "fopra-slides"
  type: website
  output-dir: docs

bibliography: specifics/bib-local.bib
csl: specifics/apa7.csl



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



website:
  sidebar:
      search: true
  navbar:
    left:
      - href: fopro-thema01.qmd
        text: Organisatorisches
      - href: fopro-thema02.qmd
        text: Rahmen
    search: true
